[package]
name = "rpc-lib"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
rpc-lib-derive = { version = "=0.1.1", path = "rpc-lib-derive" }

[workspace]
members = [
    "rpc-lib-derive",
]
